### PR TITLE
Support C++17

### PR DESCRIPTION
**Pull request by hogabrie**

### CODE REVIEW

**Comment by remod** [comment]
Thanks! Any reason we are not directly going for C++20, at least for internal code? :)

**Comment by hogabrie** [comment]
Not sure how good the support is in GCC 9,3?

**Comment by remod** [comment]
There are [quite some features](https://en.cppreference.com/w/cpp/20) which will only be supported with 10 or 11.

However, should that stop us from still using C++20 as default? We all use the same compiler, so if it does not compile, you don't use the feature ;) Also, Yoshua measured a quite significant performance improvement just by changing from C++14 to C++17, without any code changes. We might benefit again when going to C++20.

**Comment by YoshuaNava** [comment]
I just stumbled into this PR. I agree with @remod, C++17 with its [aligned new](https://www.cppstories.com/2019/08/newnew-align/) provided us with many gains with little effort star_struck (both in performance and safety of the code).

Regarding switching to C++20, it could also be quite interesting, but I lack the experience to say more.

**Comment by hogabrie** [comment]
I would first try out 20 before we update our guidelines :smile: Maybe something for when we switch to 22.04? Can we even as there is no more ROS1 release? :see_no_evil:

**Pull request merged**
